version: "3.5"
services:
  app:
    build:
      context: .
    environment:
      - TZ=Europe/Amsterdam
    image: ${REGISTRY:-localhost:5001}/${REPOSITORY:-opdrachten/amaps}:${VERSION:-latest}
    ports:
      - "3000:8080"
