version: "3.5"
services:
  serve:
    build:
      context: .
    ports:
      - 8095:8080
    image: ${REGISTRY:-localhost:5001}/${REPOSITORY:-opdrachten/amaps}:${VERSION:-latest}

  test:
    build:
      context: .
      target: build-deps
    environment:
      - SERVER_HOSTNAME=serve
    command: npm run test
    depends_on:
      - serve

  lint:
    build:
      context: .
      target: build-deps
    command: npm run lint
