version: '3.5'
services:
  build-nlmaps:
    build:
      context: ./
      dockerfile: ./Dockerfile-nlmaps
    volumes:
      - nlmapsbuild:/app/nlmaps
  test:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: build-deps
    volumes:
      - nlmapsbuild:/app/test/nlmaps
    ports:
      - 8092:8080
    command: npm run test
  watch-test:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: build-deps
    depends_on:
      - build-nlmaps
    volumes:
      - './scripts:/app/scripts'
      - './test:/app/test'
      - nlmapsbuild:/app/test/nlmaps
    command: npm run watch-test
  lint:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: build-deps
    command: npm run lint
    depends_on:
      - build-nlmaps
    volumes:
      - nlmapsbuild:/app/test/nlmaps
  serve:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - build-nlmaps
    volumes:
      - nlmapsbuild:/usr/share/nginx/html/nlmaps
    expose:
      - 80
    ipc: host
volumes:
  nlmapsbuild:
